# netlify.toml (ללא build כלל)

[[headers]]
for = "/*"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"
  Content-Security-Policy = "frame-ancestors 'self'"
  Permissions-Policy = "geolocation=(), microphone=()"
  Referrer-Policy = "strict-origin-when-cross-origin"
  X-Content-Type-Options = "nosniff"
  X-Frame-Options = "SAMEORIGIN"

[[redirects]]
from = "http://comfass.com/*"
to = "https://www.comfass.com/:splat"
status = 301
force = true
