[build]
  command = "npm run build"
  publish = "."

# כותרות ואבטחה (אופציונלי)
[[headers]]
for = "/*"
  [headers.values]
  Content-Security-Policy = "frame-ancestors 'self'"
  Permissions-Policy = "geolocation=(), microphone=()"
  Referrer-Policy = "strict-origin-when-cross-origin"
  X-Content-Type-Options = "nosniff"
  X-Frame-Options = "SAMEORIGIN"

# אל תשים Cache-Control גלובלי על /*

# קאש ארוך רק לקבצי תמונות/מודלים כבדים
[[headers]]
for = "/images/*"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/models/*"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

# CSS/JS ללא hashing – קאש קצר
[[headers]]
for = "/**/*.css"
  [headers.values]
  Cache-Control = "public, max-age=300"

[[headers]]
for = "/**/*.js"
  [headers.values]
  Cache-Control = "public, max-age=300"


[[redirects]]
from = "http://comfass.com/*"
to = "https://www.comfass.com/:splat"
status = 301
force = true

[[redirects]]
from = "https://comfass.com/*"
to = "https://www.comfass.com/:splat"
status = 301
force = true
