[build]
  command = "npm run build"
  publish = "."

# =========================
# Security headers (global)
# =========================
[[headers]]
  for = "/*"
  [headers.values]
  # אבטחה בסיסית
  X-Content-Type-Options = "nosniff"
  Referrer-Policy = "strict-origin-when-cross-origin"
  Permissions-Policy = "geolocation=(), microphone=(), camera=()"
  # הפעל HSTS רק אם כל האתר תמיד HTTPS (מומלץ בדומיין שלך)
  Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

[[headers]]
  for = "/*"
  [headers.values]
  Content-Security-Policy = """
    default-src 'self';

    script-src 'self' 'unsafe-inline' 'unsafe-eval'
      https://unpkg.com
      https://code.jquery.com
      https://comfass-com.disqus.com
      https://*.disqus.com
      https://*.disquscdn.com
      https://www.gstatic.com
      https://bringthemhomenow.net;

    /* חשוב – לאפשר סגנונות אינליין גם ברמת אלמנט וגם ברמת מאפיין */
    style-src       'self' 'unsafe-inline' https://fonts.googleapis.com https://unpkg.com;
    style-src-elem  'self' 'unsafe-inline' https://fonts.googleapis.com https://unpkg.com;
    style-src-attr  'self' 'unsafe-inline';

    font-src   'self' https://fonts.gstatic.com;
    img-src    'self' data: blob: https:;
    connect-src 'self' blob: data:
      https://comfass-com.disqus.com
      https://*.disqus.com
      https://*.disquscdn.com
      https://links.services.disqus.com
      https://www.gstatic.com
      https://formspree.io
      https://*.formspree.io
      https://bringthemhomenow.net;
    frame-src  'self' https://disqus.com https://*.disqus.com https://*.disquscdn.com;
    worker-src 'self' blob:;
    media-src  'self' blob: data: https:;
    object-src 'none';
    base-uri 'self';
    form-action 'self' https://formspree.io https://*.formspree.io;
    frame-ancestors 'self';
  """

[[plugins]]
package = "@netlify/plugin-sitemap"

# =========================
# Caching policy
# =========================

# HTML – תמיד לבדוק עדכון
[[headers]]
  for = "/"
  [headers.values]
  Cache-Control = "no-cache"

[[headers]]
  for = "/*.html"
  [headers.values]
  Cache-Control = "no-cache"

# נכסים סטטיים עם שמות יציבים/מופינגרפרינטים – קאש ארוך
[[headers]]
  for = "/css/*"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/js/*"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/img/*"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/models/*"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

# סוגי קבצים בשורש (סמלים/פונטים/wasm וכו')
[[headers]]
  for = "/*.ico"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.svg"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.png"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.jpg"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.webmanifest"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.woff2"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.wasm"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

# אם יש תיקיית פונטים ייעודית
[[headers]]
  for = "/fonts/*"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

# =========================
# Redirects (www + https)
# =========================
[[redirects]]
  from = "http://comfass.com/*"
  to   = "https://www.comfass.com/:splat"
  status = 301
  force  = true

[[redirects]]
  from = "https://comfass.com/*"
  to   = "https://www.comfass.com/:splat"
  status = 301
  force  = true
