[build]
  command = "npm run build"
  publish = "."

# === Security & Defaults ===
[[headers]]
  for = "/*"
  [headers.values]
  # אל תשתמש ב X-Frame-Options; שולטים בזה דרך CSP (frame-ancestors)
  X-Content-Type-Options = "nosniff"
  Referrer-Policy = "strict-origin-when-cross-origin"
  Permissions-Policy = "geolocation=(), microphone=(), camera=()"
  # הפעל HSTS רק אם כל האתר תמיד על HTTPS (לרוב כן):
  Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

  # CSP: עדכן רק אם תוסיף/תסיר ספקים.
  # שים לב: השארתי 'unsafe-inline' זמנית בגלל AOS/jQuery-init שתכף נוציא לקובץ חיצוני (ראה סעיף 2).
  Content-Security-Policy = """
    default-src 'self';
    img-src 'self' data: https:;
    font-src 'self' https://fonts.gstatic.com;
    style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://unpkg.com https://cdn.tailwindcss.com;
    script-src 'self' 'unsafe-inline' 'unsafe-eval'
      https://unpkg.com
      https://code.jquery.com
      https://comfass-com.disqus.com
      https://*.disquscdn.com
      https://cdn.tailwindcss.com;
    connect-src 'self' https://comfass-com.disqus.com https://*.disquscdn.com;
    frame-ancestors 'self';
    base-uri 'self';
    form-action 'self'
  """

# === Caching ===
# HTML – קאש קצר/בדיקת עדכונים בכל טעינה
[[headers]]
  for = "/*.html"
  [headers.values]
  Cache-Control = "no-cache"

# זה יתפוס גם את index.html בשורש
[[headers]]
  for = "/"
  [headers.values]
  Cache-Control = "no-cache"

# סטטיים עם fingerprint — קאש ארוך
[[headers]]
  for = "/css/*"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/js/*"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/img/*"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/models/*"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

# === Redirects ===
[[redirects]]
  from = "http://comfass.com/*"
  to = "https://www.comfass.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://comfass.com/*"
  to = "https://www.comfass.com/:splat"
  status = 301
  force = true
